### ISSUE TITLE
Seeing `Cannot find module 'typesafe-react-router'` issues in 2.2.0

### ISSUE THREAD

**Issue by jasonraimondi** [AveroLLC/typesafe-react-router#7]
I had just upgraded node modules and noticed that typesafe-react-router was updated.

Builds are all of a sudden causing an issue:

```
ERROR in ./src/routes.ts
Module not found: Error: Can't resolve 'typesafe-react-router' in '/Users/jason/go/src/***/***/projectname/src'
```

I created a demo project and had the same problems: 

https://github.com/jasonraimondi/trr-issue-example-repo

I was able to hard version to 2.0.0 so it is not a huge problem, but it does seem to be consistently happening in separate projects of mine, so it may start revealing itself to others.

**Comment by autoric** [comment]
Hey @jasonraimondi - thanks for the issue and the demo project. This was due to me removing rollup from the build process without correctly updating the main file in the package.json.

This should be fixed in version `2.2.1` as of ~25 minutes ago. Very sorry for the inconvenience!
